-- Create the event store tables
CREATE TABLE IF NOT EXISTS DOMAIN_EVENT_ENTRY
(
    GLOBAL_INDEX
    BIGSERIAL
    NOT
    NULL,
    EVENT_IDENTIFIER
    VARCHAR
(
    255
) NOT NULL,
    META_DATA BYTEA,
    PAYLOAD BYTEA NOT NULL,
    PAYLOAD_REVISION VARCHAR
(
    255
),
    PAYLOAD_TYPE VARCHAR
(
    255
) NOT NULL,
    TIME_STAMP VARCHAR
(
    255
) NOT NULL,
    AGGREGATE_IDENTIFIER VARCHAR
(
    255
) NOT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,
    TYPE VARCHAR
(
    255
),
    PRIMARY KEY
(
    AGGREGATE_IDENTIFIER,
    GLOBAL_INDEX
),
    UNIQUE
(
    AGGREGATE_IDENTIFIER,
    SEQUENCE_NUMBER
)
    ) PARTITION BY HASH
(
    AGGREGATE_IDENTIFIER
);

-- Create partitions for the event store
CREATE TABLE DOMAIN_EVENT_ENTRY_0 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    0
);
CREATE TABLE DOMAIN_EVENT_ENTRY_1 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    1
);
CREATE TABLE DOMAIN_EVENT_ENTRY_2 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    2
);
CREATE TABLE DOMAIN_EVENT_ENTRY_3 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    3
);
CREATE TABLE DOMAIN_EVENT_ENTRY_4 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    4
);
CREATE TABLE DOMAIN_EVENT_ENTRY_5 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    5
);
CREATE TABLE DOMAIN_EVENT_ENTRY_6 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    6
);
CREATE TABLE DOMAIN_EVENT_ENTRY_7 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    7
);
CREATE TABLE DOMAIN_EVENT_ENTRY_8 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    8
);
CREATE TABLE DOMAIN_EVENT_ENTRY_9 PARTITION OF DOMAIN_EVENT_ENTRY FOR VALUES WITH
(
    MODULUS
    10,
    REMAINDER
    9
);

-- Create snapshot table
CREATE TABLE IF NOT EXISTS SNAPSHOT_EVENT_ENTRY
(
    AGGREGATE_IDENTIFIER
    VARCHAR
(
    255
) NOT NULL,
    SEQUENCE_NUMBER BIGINT NOT NULL,
    TYPE VARCHAR
(
    255
) NOT NULL,
    EVENT_IDENTIFIER VARCHAR
(
    255
) NOT NULL,
    META_DATA BYTEA,
    PAYLOAD BYTEA NOT NULL,
    PAYLOAD_REVISION VARCHAR
(
    255
),
    PAYLOAD_TYPE VARCHAR
(
    255
) NOT NULL,
    TIME_STAMP VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    AGGREGATE_IDENTIFIER,
    SEQUENCE_NUMBER
)
    );

-- Create token entry table
CREATE TABLE IF NOT EXISTS TOKEN_ENTRY
(
    PROCESSOR_NAME
    VARCHAR
(
    255
) NOT NULL,
    SEGMENT INTEGER NOT NULL,
    OWNER VARCHAR
(
    255
),
    TIMESTAMP VARCHAR
(
    255
) NOT NULL,
    TOKEN BYTEA,
    TOKEN_TYPE VARCHAR
(
    255
),
    PRIMARY KEY
(
    PROCESSOR_NAME,
    SEGMENT
)
    );
